- apply
- datetimes
- group
- aggregate

In [46]:
import pandas as pd

df = pd.read_csv("./data/french-ambs.csv")
df

,id,name,place,year,lat,long,lat_long
0,0,"Richer, Christophe",Denmark,1543,55.68,12.57,"55.68, 12.57"
1,1,"Richer, Christophe",Denmark,1541,55.68,12.57,"55.68, 12.57"
2,2,"Danzay, Charles de",Denmark,1561,55.68,12.57,"55.68, 12.57"
3,3,"Danzay, Charles de",Denmark,1563,55.68,12.57,"55.68, 12.57"
4,4,"Danzay, Charles de",Denmark,1582,55.68,12.57,"55.68, 12.57"
...,...,...,...,...,...,...,...
864,864,"Canossa, Louis de",Venice,1526,45.44,12.33,"45.44, 12.33"
865,865,"Vigier, Jacques",Swiss Cantons,1597,46.94,7.45,"46.94, 7.45"
866,866,"De Selve, Georges",Venice,1537,45.44,12.33,"45.44, 12.33"
867,867,"Noailles, François de, Bishop of Dax",Venice,1559,45.44,12.33,"45.44, 12.33"
868,868,"Calvimont, Jean de",Holy Roman Empire,1525,48.21,16.36,"48.21, 16.36"

In [47]:
from random import choice

# import random
# random.choice
# this is overkill
# only import what you need

df["date_start"] = f"{df["year"]}-{choice(range(1,13)):02d}-{choice(range(1,29)):02d}" # datetime object: "yyyy-mm-dd"
df

,id,name,place,year,lat,long,lat_long,date_start
0,0,"Richer, Christophe",Denmark,1543,55.68,12.57,"55.68, 12.57",0 1543\n1 1541\n2 1561\n3 ...
1,1,"Richer, Christophe",Denmark,1541,55.68,12.57,"55.68, 12.57",0 1543\n1 1541\n2 1561\n3 ...
2,2,"Danzay, Charles de",Denmark,1561,55.68,12.57,"55.68, 12.57",0 1543\n1 1541\n2 1561\n3 ...
3,3,"Danzay, Charles de",Denmark,1563,55.68,12.57,"55.68, 12.57",0 1543\n1 1541\n2 1561\n3 ...
4,4,"Danzay, Charles de",Denmark,1582,55.68,12.57,"55.68, 12.57",0 1543\n1 1541\n2 1561\n3 ...
...,...,...,...,...,...,...,...,...
864,864,"Canossa, Louis de",Venice,1526,45.44,12.33,"45.44, 12.33",0 1543\n1 1541\n2 1561\n3 ...
865,865,"Vigier, Jacques",Swiss Cantons,1597,46.94,7.45,"46.94, 7.45",0 1543\n1 1541\n2 1561\n3 ...
866,866,"De Selve, Georges",Venice,1537,45.44,12.33,"45.44, 12.33",0 1543\n1 1541\n2 1561\n3 ...
867,867,"Noailles, François de, Bishop of Dax",Venice,1559,45.44,12.33,"45.44, 12.33",0 1543\n1 1541\n2 1561\n3 ...
868,868,"Calvimont, Jean de",Holy Roman Empire,1525,48.21,16.36,"48.21, 16.36",0 1543\n1 1541\n2 1561\n3 ...

In [48]:
df = df.drop(columns=["date_start","lat_long"])
df = df[["name","place","year"]]
df

                                     name              place  year
0                      Richer, Christophe            Denmark  1543
1                      Richer, Christophe            Denmark  1541
2                      Danzay, Charles de            Denmark  1561
3                      Danzay, Charles de            Denmark  1563
4                      Danzay, Charles de            Denmark  1582
..                                    ...                ...   ...
864                     Canossa, Louis de             Venice  1526
865                       Vigier, Jacques      Swiss Cantons  1597
866                     De Selve, Georges             Venice  1537
867  Noailles, François de, Bishop of Dax             Venice  1559
868                    Calvimont, Jean de  Holy Roman Empire  1525

[869 rows x 3 columns]

In [49]:
# apply on data series

df["date_start"] = df["year"].apply(lambda x: f"{x}-{choice(range(1,13)):02d}-{choice(range(1,29)):02d}")
df

                                     name              place  year  date_start
0                      Richer, Christophe            Denmark  1543  1543-11-08
1                      Richer, Christophe            Denmark  1541  1541-05-02
2                      Danzay, Charles de            Denmark  1561  1561-03-04
3                      Danzay, Charles de            Denmark  1563  1563-10-11
4                      Danzay, Charles de            Denmark  1582  1582-09-08
..                                    ...                ...   ...         ...
864                     Canossa, Louis de             Venice  1526  1526-08-19
865                       Vigier, Jacques      Swiss Cantons  1597  1597-07-18
866                     De Selve, Georges             Venice  1537  1537-06-25
867  Noailles, François de, Bishop of Dax             Venice  1559  1559-10-20
868                    Calvimont, Jean de  Holy Roman Empire  1525  1525-12-06

[869 rows x 4 columns]

In [50]:
import numpy as np

def get_date_start(row):
    rows = df.loc[
        (df["place"] == row["place"]) &
        (df["name"] == row["name"]) &
        (df["year"] == row["year"] - 1)
    ]
    if len(rows) > 0:
        return np.nan
    date_string = f"{row["year"]}-{choice(range(1,13)):02d}-{choice(range(1,29)):02d}"
    return date_string

df["date_start"] = df.apply(get_date_start, axis=1)
df

                                     name              place  year  date_start
0                      Richer, Christophe            Denmark  1543         NaN
1                      Richer, Christophe            Denmark  1541  1541-01-22
2                      Danzay, Charles de            Denmark  1561         NaN
3                      Danzay, Charles de            Denmark  1563         NaN
4                      Danzay, Charles de            Denmark  1582         NaN
..                                    ...                ...   ...         ...
864                     Canossa, Louis de             Venice  1526         NaN
865                       Vigier, Jacques      Swiss Cantons  1597         NaN
866                     De Selve, Georges             Venice  1537         NaN
867  Noailles, François de, Bishop of Dax             Venice  1559         NaN
868                    Calvimont, Jean de  Holy Roman Empire  1525  1525-04-03

[869 rows x 4 columns]

In [51]:
def get_date_end(row):
    rows = df.loc[
        (df["place"] == row["place"]) &
        (df["name"] == row["name"]) &
        (df["year"] == row["year"] + 1)
    ]
    if len(rows) > 0:
        return np.nan
    date_string = f"{row["year"]}-{choice(range(1,13)):02d}-{choice(range(1,29)):02d}"
    return date_string

df["date_end"] = df.apply(get_date_end, axis=1)
df

,name,place,year,date_start,date_end
0,"Richer, Christophe",Denmark,1543,NaN,NaN
1,"Richer, Christophe",Denmark,1541,1541-01-22,NaN
2,"Danzay, Charles de",Denmark,1561,NaN,NaN
3,"Danzay, Charles de",Denmark,1563,NaN,NaN
4,"Danzay, Charles de",Denmark,1582,NaN,NaN
...,...,...,...,...,...
864,"Canossa, Louis de",Venice,1526,NaN,1526-01-23
865,"Vigier, Jacques",Swiss Cantons,1597,NaN,1597-08-09
866,"De Selve, Georges",Venice,1537,NaN,NaN
867,"Noailles, François de, Bishop of Dax",Venice,1559,NaN,NaN
868,"Calvimont, Jean de",Holy Roman Empire,1525,1525-04-03,NaN

In [52]:
# sort values

df = df.sort_values(["place","name","year"], ascending=True)
df

                    name    place  year  date_start    date_end
422   Danzay, Charles de  Denmark  1557  1557-10-08         NaN
638   Danzay, Charles de  Denmark  1558         NaN         NaN
704   Danzay, Charles de  Denmark  1559         NaN         NaN
421   Danzay, Charles de  Denmark  1560         NaN         NaN
2     Danzay, Charles de  Denmark  1561         NaN         NaN
..                   ...      ...   ...         ...         ...
112     Séguier, Antoine   Venice  1599         NaN         NaN
531     Séguier, Antoine   Venice  1600         NaN  1600-06-23
353  d'Armagnac, Georges   Venice  1536  1536-02-19         NaN
756  d'Armagnac, Georges   Venice  1537         NaN         NaN
757  d'Armagnac, Georges   Venice  1538         NaN  1538-04-05

[869 rows x 5 columns]

In [53]:
# bfill(), ffill()

df["date_start"] = df["date_start"].ffill()
df["date_end"] = df["date_end"].bfill()
df

                    name    place  year  date_start    date_end
422   Danzay, Charles de  Denmark  1557  1557-10-08  1589-07-12
638   Danzay, Charles de  Denmark  1558  1557-10-08  1589-07-12
704   Danzay, Charles de  Denmark  1559  1557-10-08  1589-07-12
421   Danzay, Charles de  Denmark  1560  1557-10-08  1589-07-12
2     Danzay, Charles de  Denmark  1561  1557-10-08  1589-07-12
..                   ...      ...   ...         ...         ...
112     Séguier, Antoine   Venice  1599  1598-02-28  1600-06-23
531     Séguier, Antoine   Venice  1600  1598-02-28  1600-06-23
353  d'Armagnac, Georges   Venice  1536  1536-02-19  1538-04-05
756  d'Armagnac, Georges   Venice  1537  1536-02-19  1538-04-05
757  d'Armagnac, Georges   Venice  1538  1536-02-19  1538-04-05

[869 rows x 5 columns]

In [54]:
from datetime import datetime
fmt = "%Y-%m-%d"

df["date_end"] = df["date_end"].apply(lambda x: datetime.strptime(x, fmt))
df["date_start"] = df["date_start"].apply(lambda x: datetime.strptime(x, fmt))
df

,name,place,year,date_start,date_end
422,"Danzay, Charles de",Denmark,1557,1557-10-08 00:00:00,1589-07-12 00:00:00
638,"Danzay, Charles de",Denmark,1558,1557-10-08 00:00:00,1589-07-12 00:00:00
704,"Danzay, Charles de",Denmark,1559,1557-10-08 00:00:00,1589-07-12 00:00:00
421,"Danzay, Charles de",Denmark,1560,1557-10-08 00:00:00,1589-07-12 00:00:00
2,"Danzay, Charles de",Denmark,1561,1557-10-08 00:00:00,1589-07-12 00:00:00
...,...,...,...,...,...
112,"Séguier, Antoine",Venice,1599,1598-02-28 00:00:00,1600-06-23 00:00:00
531,"Séguier, Antoine",Venice,1600,1598-02-28 00:00:00,1600-06-23 00:00:00
353,"d'Armagnac, Georges",Venice,1536,1536-02-19 00:00:00,1538-04-05 00:00:00
756,"d'Armagnac, Georges",Venice,1537,1536-02-19 00:00:00,1538-04-05 00:00:00
757,"d'Armagnac, Georges",Venice,1538,1536-02-19 00:00:00,1538-04-05 00:00:00

In [55]:
df["date_end"].apply(lambda x: x.year)

422    1589
638    1589
704    1589
421    1589
2      1589
       ...
112    1600
531    1600
353    1538
756    1538
757    1538
Name: date_end, Length: 869, dtype: int64

In [56]:
placesdf = df.groupby(["place"]).count()
placesdf

                   name  year  date_start  date_end
place
Denmark              40    40          40        40
England              93    93          93        93
Ferrara               3     3           3         3
Geneva                2     2           2         2
Grisons              77    77          77        77
Holy Roman Empire    81    81          81        81
Netherlands          45    45          45        45
Ottoman Empire       89    89          89        89
Poland                7     7           7         7
Portugal             56    56          56        56
Rome                 82    82          82        82
Savoy                 4     4           4         4
Saxony                3     3           3         3
Scotland             22    22          22        22
Spain                35    35          35        35
Swiss Cantons       131   131         131       131
Tuscany               3     3           3         3
Venice               96    96          96        96

In [57]:
placesdf = df.groupby(["place"]).agg(
    {
    "name": "count",
    "year": "min",
    "year": "max",
    }
).reset_index()
placesdf

                place  name  year
0             Denmark    40  1589
1             England    93  1600
2             Ferrara     3  1554
3              Geneva     2  1560
4             Grisons    77  1588
5   Holy Roman Empire    81  1600
6         Netherlands    45  1600
7      Ottoman Empire    89  1600
8              Poland     7  1574
9            Portugal    56  1578
10               Rome    82  1589
11              Savoy     4  1574
12             Saxony     3  1572
13           Scotland    22  1588
14              Spain    35  1589
15      Swiss Cantons   131  1600
16            Tuscany     3  1529
17             Venice    96  1600

In [58]:
placesdf = df.groupby(["place"]).agg(
    num=("year", "count"),
    min_year=("year", "min"),
    max_year=("year", "max"),
    ambs=("name", "unique"),
    num_ambs=("name", "nunique")
).reset_index().sort_values(["num"], ascending=True)
placesdf

,place,num,min_year,max_year,ambs,num_ambs
3,Geneva,2,1559,1560,"[Boistaillé, Jean Hurault de]",1
2,Ferrara,3,1535,1554,"[Du Gabre, Dominique, Langeac, Jean de]",2
12,Saxony,3,1570,1572,"[Schomberg, Gaspard de]",1
16,Tuscany,3,1527,1529,"[Dodieu, Claude]",1
11,Savoy,4,1528,1574,"[Des Barres, Louis, Henri d'Angouleme, Sr. de ...",3
8,Poland,7,1572,1574,"[Fayes, Jacques, sr d'Espesses, Lansac, Guy de...",5
13,Scotland,22,1548,1588,"[Clutin, Henri, Courcelles, Baron de, Du Croc,...",4
14,Spain,35,1559,1589,"[Fourquevaux, Raymond de Beccarie de Pavie, Ba...",5
0,Denmark,40,1541,1589,"[Danzay, Charles de, Richer, Christophe]",2
6,Netherlands,45,1529,1600,"[Blatier, Claude, Bochetel, Jacques, Choary, P...",12
9,Portugal,56,1522,1578,"[De Caix, Honoré, De Seurre, Miguel, Nicot, Je...",5
4,Grisons,77,1525,1588,"[Bellièvre, Pomponne de, Cambray, Jean-Jacques...",13
5,Holy Roman Empire,81,1519,1600,"[Ancel, Guillaume, Bochetel, Bernardin, Calvim...",15
10,Rome,82,1513,1589,"[Adhemar, Louis, Babou, Philibert, Carmain, Pa...",24
7,Ottoman Empire,89,1535,1600,"[Berthier, Sébastien, Cambray, Jacques de, Cot...",20
1,England,93,1516,1600,"[Bapaume, Robert de, Bochetel, Jacques, Castel...",26
17,Venice,96,1516,1600,"[Boistaillé, Jean Hurault de, Canossa, Louis d...",20
15,Swiss Cantons,131,1522,1600,"[Bellièvre, Jean de, sr. de Hautefort, Bellièv...",27

In [60]:
placesdf = df.groupby(["place","name"]).agg(
    num=("year", "count"),
    min_year=("year", "min"),
    max_year=("year", "max")
).reset_index().sort_values(["num"], ascending=False)
placesdf

,place,name,num,min_year,max_year
0,Denmark,"Danzay, Charles de",33,1557,1589
96,Portugal,"De Caix, Honoré",33,1522,1558
147,Swiss Cantons,"Daugerant, Louis",29,1522,1549
44,Holy Roman Empire,"Ancel, Guillaume",25,1576,1600
173,Venice,"Du Ferrier, Arnaud",16,1564,1582
...,...,...,...,...,...
159,Swiss Cantons,"Tugginer,Guillaume",1,1563,1563
157,Swiss Cantons,"Mendoza, Diego de",1,1562,1562
32,Grisons,"Cambray, Jean-Jacques de",1,1558,1558
56,Holy Roman Empire,"Seigneur d'Orval, governor of Champagne",1,1519,1519
52,Holy Roman Empire,"L'Aubespine, Sébastien de",1,1556,1556